[package]
name = "rustdesk-server"
version = "1.0.0"
authors = ["rustdesk <info@rustdesk.com>"]
edition = "2018"
description = "A remote control software."

[dependencies]
uuid = { version = "0.8", features = ["v4"] }
hbb_common = { path = "libs/hbb_common" }
tracing = "0.1"
tracing-subscriber = "0.2"



[[example]]
name = "demo1"
path = "apps/demo1.rs"

[[example]]
name = "demo2"
path = "apps/demo2.rs"

[[example]]
name = "demo3"
path = "apps/demo3.rs"



